### ISSUE TITLE
When loading by PDB ID, Pymol won't work

### ISSUE THREAD

**Issue by hikarino-my** [yakomaxa/PyMOL-Wasm#20]
Please add these event listners after structure loading.

https://github.com/yakomaxa/PyMOL-Wasm/blob/5662d9cd13bec27c966c78a7db4468a3a5cc7625/index.html#L87-L91

**Comment by hikarino-my** [comment]
Sorry that wasn't the one.
Maybe this.
https://github.com/yakomaxa/PyMOL-Wasm/blob/5662d9cd13bec27c966c78a7db4468a3a5cc7625/index.html#L804

**Comment by yakomaxa** [comment]
Thank you for clarifying the symptom. 
We found that PyMOL launches in the following ways.
(1) Press "Press here to launch" first
(2) Load pdb by ID
(3) Press "Press here to launch" again
(4) Move mouse pointer to the canvas

However, this is not intended behavior and problematic, so I should fix this. It would be good if hitting "Load by PDB ID" directly launches PyMOL window.

**Comment by hikarino-my** [comment]
I think this can be fixed by placing that eventlistener around here for now.
https://github.com/yakomaxa/PyMOL-Wasm/blob/5662d9cd13bec27c966c78a7db4468a3a5cc7625/index.html#L346

At the refactoring phase, it should be placed into something like "initializePyMOL" function.

For this
>It would be good if hitting "Load by PDB ID" directly launches PyMOL window.

I perfectly agree with you. Adding the same function to the drag&drop box and remove the launch button will be good.

**Comment by hikarino-my** [comment]
Also, input to a input tag will be also captured by this function.
https://github.com/yakomaxa/PyMOL-Wasm/blob/5662d9cd13bec27c966c78a7db4468a3a5cc7625/index.html#L804
