### ISSUE TITLE
[bug] Right panel disappears after showing as licorice

### ISSUE THREAD

**Issue by hikarino-my** [yakomaxa/PyMOL-Wasm#9]
When opening [this structure](https://www.rcsb.org/structure/3rh8) and show it as licorice, the right panel disappears.

**Comment by yakomaxa** [comment]
Thank you for reporting this problem. I'm checking why and which ingredient of this structure specifically causes the problem. If you find any other example to cause this, please share them here.

**Comment by hikarino-my** [comment]
Well, actually...
The bug can be reproduced with a PDB file containing only the following content.
```
HETATM 2495  O   HOH D   1      -7.311   6.502  33.153  1.00 22.30           O  
```

**Comment by yakomaxa** [comment]
Thank you for detailed investigation! This is consistent with my observation that removing hetatm stops the problem from happening. Especially, water parts seem doing something bad as you've shown.

**Comment by yakomaxa** [comment]
Other structure with similarly isolated (non-bonded) atom like ion also cause this problem. I'll investigate why and fix this as soon as possible.

**Comment by yakomaxa** [comment]
I've made an alternative page to debug

https://yakomaxa.github.io/PyMOL-Wasm/debugging.html

This page will be frequently modified and will be merged to main index.html if successfully debugged.

**Comment by yakomaxa** [comment]
I fixed this problem (at least symptomatically) and now merging it to the main index.html. The problem was caused by forcing stick representation for every hetatom. The root cause of this symptom will be fixed.

**Comment by hikarino-my** [comment]
Thanks for your quick reply.
I've confirmed that water molecules are now displayed, although I'm afraid the right panel still disappears after changing the representation.

**Comment by yakomaxa** [comment]
I've also re-confirmed the problem... I'll try to solve this on this weekend if possible!

**Comment by yakomaxa** [comment]
Memo: nb_sphere is doing something bad.

**Comment by yakomaxa** [comment]
I solved this problem by cmd.set("nb_spheres_use_shader", 2) and merged changes to main index.html. Please reload the page and try it.

**Comment by hikarino-my** [comment]
I have confirmed that this bug has been resolved.
Thank you!
